#ifndef  __VMM_H
#define __VMM_H

#define HCR_VM_BIT                 (1UL << 0)
#define HCR_SWIO_BIT               (1UL << 1)
#define HCR_PTW_BIT                (1UL << 2)
#define HCR_FMO_BIT                (1UL << 3)
#define HCR_IMO_BIT                (1UL << 4)
#define HCR_AMO_BIT                (1UL << 5)
#define HCR_VF_BIT                 (1UL << 6)
#define HCR_VI_BIT                 (1UL << 7)
#define HCR_VSE_BIT                (1UL << 8)
#define HCR_FB_BIT                 (1UL << 9)
#define HCR_BSU_BIT                (1UL << 10)
#define HCR_DC_BIT                 (1UL << 12)
#define HCR_TWI_BIT                (1UL << 13)
#define HCR_TWE_BIT                (1UL << 14)
#define HCR_TID0_BIT               (1UL << 15)
#define HCR_TID1_BIT               (1UL << 16)
#define HCR_TID2_BIT               (1UL << 17)
#define HCR_TID3_BIT               (1UL << 18)
#define HCR_TSC_BIT                (1UL << 19)
#define HCR_TIDCP_BIT              (1UL << 20)
#define HCR_TACR_BIT               (1UL << 21)
#define HCR_TSW_BIT                (1UL << 22)
#define HCR_TPC_BIT                (1UL << 23)
#define HCR_TPU_BIT                (1UL << 24)
#define HCR_TTLB_BIT               (1UL << 25)
#define HCR_TVM_BIT                (1UL << 26)
#define HCR_TGE_BIT                (1UL << 27)
#define HCR_TDZ_BIT                (1UL << 28)
#define HCR_HCD_BIT                (1UL << 29)
#define HCR_TRVM_BIT               (1UL << 30)
#define HCR_RW_BIT                 (1UL << 31)
#define HCR_CD_BIT                 (1UL << 32)
#define HCR_ID_BIT                 (1UL << 33)
#define HCR_TERR_BIT               (1UL << 36)
#define HCR_TEA_BIT                (1UL << 37)
#define HCR_MIOCNCE_BIT            (1UL << 38)
#define HCR_APK_BIT                (1ULL << 40)
#define HCR_API_BIT                (1ULL << 41)

void vmm_init(void);

#endif
